version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "image-recognition"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-26zkytah02i5"
s3_prefix = "image-recognition"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
